### PR TITLE
Allow upgrade of composer version from .env

### PR DESCRIPTION
**Pull request by smulvih2**
This has not been tested yet, just for reference.

### CODE REVIEW

**Comment by smulvih2** [comment]
Would be nice to start extracting some versioning to allow easier upgrades as security updates become available. This PR should allow us to specify COMPOSER_VERSION in our .env file, with a default of 2.7.9 as [requested here](https://github.com/drupalwxt/docker-scaffold/issues/44).

**Comment by chrislaick** [comment]
Tested this PR with a new drupalwxt/site-wxt project and set `COMPOSER_VERSION=2.7.7` in the .env file. The composer version in the cli and web container is showing 2.7.7, so it's working. I then proceeded to remove `COMPOSER_VERSION=2.7.7` altogether in the .env file and the default composer version 2.7.9 was downloaded and used in the new build. Working great!

There were a few docker warnings, which you are probably aware of:
6 warnings found (use docker --debug to expand):
-  LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 61)
-  LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 68)
-  LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 70)
-  LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 71)
-  SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "SSH_PRIVATE_KEY") (line 4)
-  SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "GIT_PASSWORD") (line 6)

**Comment by sylus** [comment]
Hey @smulvih2 is this ok to merge now? Since its confirming to be working was there anything you were waiting for?

**Comment by smulvih2** [comment]
@sylus this can be merged, confirmed working. We should also merge this PR for drupalwxt/site-wxt to add COMPOSER_VERSION to the .env file - [https://github.com/drupalwxt/site-wxt/pull/37](https://github.com/drupalwxt/site-wxt/pull/37)

**Pull request merged**
