### PR TITLE
Add purge/ban to Varnish config

### PR DESCRIPTION
**Pull request by smulvih2**
This is just to capture changes required to get drupal/purge to work with Varnish. Still need to test this on 10.2.x since my project's Varnish config has deviated from this branch.

### CODE REVIEW

**Comment by smulvih2** [comment]
I had to add IPv6 to the ACL to get this to work. IPv4 localhost was not working.

I used `varnishlog` to see the value of `client.ip` in real-time: `varnishlog -g request -i ReqStart`

This indicated a request coming from the IPv6 localhost address ::1. These requests are coming directly from the Varnish server itself, such as when using `curl` from the command line on the Varnish server. Once I added the IPv6 localhost it started working.

I increased TTL from 5 minutes to 30 days. This is a reasonable default for Varnish, but also means drupal/purge or similar solution must be added in order to invalidate the cache.

Thanks @joejoseph00 for help with this solution and testing.

**Comment by joejoseph00** [comment]
Awesome!  Great to get this fixed!

**Comment by joejoseph00** [comment]
A potential client I talked to today is going to be doing a scaffold build soon, recommend merging this soon so that they start off with this included.

**Comment by smulvih2** [comment]
Yep, will need to test this first, so just including this PR here for reference until I have time to test against plain 10.2.x branch setup.

**Comment by smulvih2** [comment]
@sylus this is ready for merging. This config change has been tested and in Prod for a month now and no reported issues.

**Pull request merged**
